### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by sagarneo11** [dmachat/angularjs-d3-chartbuilder#4]
Hi,

i am currently using this git for my one project, i wanted to contribute but i am not sure how i can do that, means i am not much familier with git so i dont know how i can do this. please guide... i can provide a new UI with few new improvements on which i am working right now

Regards
Sagar

**Comment by dmachat** [comment]
Hey @sagarneo11, thanks for your interest in contributing. I've stopped active development on this particular project, but you can find an active descendent of it at https://github.com/alleyinteractive/simplechart. If you'd rather build off this version, feel free to fork it and I can add a link here to point people to the improved version on your github.

**Comment by sagarneo11** [comment]
Hi,

thanks for reply, 

i have forked this new descendant, i will install it on my machine and will check how i can customize it... you can close this one then
